name: Telegram Clock

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'  # كل 30 دقيقة

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: إعداد بايثون
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: تثبيت المكتبات
        run: pip install telethon pytz

      - name: تشغيل time.py
        run: python time.py
